# Generated by Django 2.2 on 2021-05-22 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes_added', to='login_app.User'),
        ),
    ]
